### ISSUE TITLE
ファイルUploadできません。

### ISSUE THREAD

**Issue by ryokanoshoh** [JakeJP/FlashAir.NET#1]
「FlashAir.NET」をXamarin.iOSに入れてファイルUploadを試みていますが、「NG」で返ってきます。
ファイルアップロードの手順は以下の通りです。
1.デバイス内にローカルのバイナリファイル(sample.bin)を作成
2.アップロード前に以下の設定を行う。
　2-1.アップロード先フォルダの設定。「SetUploadDirectory(remoteDir)」
　2-2.ファイル作成日時の設定。「SetSystemTime(DateTime.Now)」
3.ファイルアップロード
　->NGと帰る。

デバッグしてみたところ、ファイルの作成及び各種設定処理は正常に行われております。
そのため、NGになる原因がわかりません。
不具合かどうか判断できないため、ご教授いただきますようお願い致します。

**Comment by JakeJP** [comment]
調べたところFlashAirのupload.cgiの扱いで修正が必要でした。

Content-Disposition の filename は必ずダブルクォーテーションで囲む必要があること。
utf-8(.NETライブラリがサポートしている）対応のfilename*は省くこと。
また、HTTPの応答についてはHTMLで返ってくるようなのでその点の扱いを変えました。

**Comment by ryokanoshoh** [comment]
Update後のリソースを更新し動作確認いたしました。
正常に動作しました。
ご対応いただき、誠にありがとうございます。

**Comment by ryokanoshoh** [comment]
日本語のファイル名がついたファイルがUploadできません。
Webで動作確認したところ、日本語のファイル名のものでもUploadできます。
昨年の改修が影響したのでしょうか？
確認のほどお願いいたします。
