### ISSUE TITLE
日本語名のファイルがUploadできません。

### ISSUE THREAD

**Issue by ryokanoshoh** [JakeJP/FlashAir.NET#2]
Xamarin.iOSから日本語名のファイルをFlashAirにUploadを
試みましたが、Uploadに失敗します。
デバッグしたところ、処理結果は「NG」で返ってきます。
しかし、FlashAirにWebでアクセスし、ブラウザで日本語名のファイルを
Uploadすることができます。
動作確認の上、修正のほどお願いいたします。

**Comment by JakeJP** [comment]
HttpHeaderの書き出しが UNICODE->ASCII 変換がかかって文字化けするようです。ブラウザがやっているようにUTF-8そのままに出力するためにややトリッキーなことをしました。Windows上では確認しましたが、Xamarinではまた挙動が違うかもしれません。

**Comment by ryokanoshoh** [comment]
ご対応いただき、誠にありがとうございます。
Xamarin上で動作確認してみます。

**Comment by ryokanoshoh** [comment]
Xamarin上で動作確認してみましたがダメでした。
こちらで少し調査してみます。

**Comment by ryokanoshoh** [comment]
色々と試してみましたが、Xamarin.iOSでは日本語ファイル名は
Uploadできないようです。おそらくiOSの仕様だと思われます。
ですので、ここでクローズします。
