### ISSUE TITLE
W-04ではUploadできません。

### ISSUE THREAD

**Issue by ryokanoshoh** [JakeJP/FlashAir.NET#3]
FlashAir SD-UWAシリーズ（W-04）でファイルUploadができません。
Debugしたところ、以下のコードの結果で「NG」と返ります。

var response = client.PostAsync(BaseUrl, content).Result.Content.ReadAsStringAsync().Result;

W-04対応の改修が必要かと思われます。
現行の仕様を確認の上、対応のほどお願いいたします。

**Comment by JakeJP** [comment]
ようやくW-04を入手したので確認できました。
Content-Dispositionヘッダーの順序が異なるだけでエラーとなる挙動のためでした。
